### ISSUE TITLE
Error: Package subpath './package.json' is not defined by "exports" in  node_modules/w3c-keyname/package.json

### ISSUE THREAD

**Issue by jet10000** [ProseMirror/prosemirror-markdown#45]
```
rollup v2.22.1
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Package subpath './package.json' is not defined by "exports" in /Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/w3c-keyname/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/w3c-keyname/package.json
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.requireRelative.resolve (/Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/require-relative/index.js:30:17)
    at tryResolve (/Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/rollup-plugin-svelte/index.js:50:19)
    at Object.resolveId (/Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/rollup-plugin-svelte/index.js:177:21)
    at /Users/user1/github/pm/frontend/svelte/prosermarkdown-editor/node_modules/rollup/dist/shared/rollup.js:18264:25

```

```
node -v
v14.5.0
```

**Comment by marijnh** [comment]
As I wrote in [this issue](https://github.com/marijnh/w3c-keyname/issues/10), that looks more like a bug in the Svelte (or the rollup Svelte plugin) code than in this package.
